import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import DarkModeContainer from "@/components/DarkModeContainer";
import ProviderContainer from "@/components/ProviderContainer";

const roboto = Roboto({
  weight: ["400", "500", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Wordle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <DarkModeContainer lang="pt-BR" className={roboto.className}>
      <body>
        <ProviderContainer>{children}</ProviderContainer>
      </body>
    </DarkModeContainer>
  );
}
